// <auto-generated />
using System;
using Kobold.TodoApp.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kobold.TodoApp.Api.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20230823034604_SeedTodoCorrige")]
    partial class SeedTodoCorrige
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Kobold.TodoApp.Api.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("Done")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2023, 8, 23, 0, 46, 3, 993, DateTimeKind.Local).AddTicks(5678),
                            Description = "Procurar receita",
                            Done = true
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2023, 8, 23, 0, 46, 3, 993, DateTimeKind.Local).AddTicks(7977),
                            Description = "Comprar ingredientes",
                            Done = true
                        },
                        new
                        {
                            Id = 3,
                            DataCriacao = new DateTime(2023, 8, 23, 0, 46, 3, 993, DateTimeKind.Local).AddTicks(8078),
                            Description = "Cozinhar receita",
                            Done = false
                        },
                        new
                        {
                            Id = 4,
                            DataCriacao = new DateTime(2023, 8, 23, 0, 46, 3, 993, DateTimeKind.Local).AddTicks(8128),
                            Description = "Servir mesa",
                            Done = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
