version: '3.4'

services:
  kobold.todoapp.api:
    image: ${DOCKER_REGISTRY-}koboldtodoappapi
    build:
      context: .
      dockerfile: src/Kobold.TodoApp.Api/Dockerfile
    depends_on:
      - db
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: supersecreto
      MYSQL_DATABASE: todos
    ports:
      - "3307:3306"
